version: '2'
services:
    web:
        image: slackbot-cmaliwal:0.0.1
        volumes:
            - .:/src        
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "7379:6379"
