version: '2'
services:
    web:
        image: slackbot-prod:0.0.1
        restart: always
        volumes:
            - .:/src        
        depends_on:
            - redis
    redis:
        image: redis
        restart: always
        ports:
            - "7379:6379"
